import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const poppins = localFont({
  src: "./fonts/Poppins-ExtraLight.ttf",
  variable: "--font-poppins-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "WB3",
  description: "Generated by create next app",
  icons: "/icons/wb3.jpeg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
